# Generated by Django 4.1.3 on 2022-11-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
