# Generated by Django 4.1.3 on 2022-12-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_updated_at_product_created_at_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at_2',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at_1',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
