# Generated by Django 4.1.3 on 2022-12-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_created_at_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at_2',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at_1',
            new_name='updated',
        ),
    ]
