# Generated by Django 4.1.3 on 2022-12-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_created_at_2_product_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_a',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_a',
        ),
    ]
