# Generated by Django 4.1.3 on 2022-12-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_rename_created_product_created_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_a',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_a',
        ),
    ]
