# Generated by Django 4.1.3 on 2022-12-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_product_created_a_remove_product_updated_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
