# Generated by Django 4.1.3 on 2022-12-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_a',
            field=models.DateTimeField(auto_now_add=True, default='Europe/Kiev', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_a',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
