# Generated by Django 4.1.3 on 2022-12-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_created_a_product_updated_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tree_id',
        ),
    ]
