# Generated by Django 4.1.3 on 2023-02-25 23:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_user'),
        ('main', '0002_alter_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta keywords')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Контактная страница',
                'verbose_name_plural': 'Контактные страницы',
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировано')),
                ('products', models.ManyToManyField(to='catalog.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Карусель товара',
                'verbose_name_plural': 'Карусель товаров',
                'ordering': ['sort'],
            },
        ),
    ]
